name: Build & publish image
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
 build-and-push-dockerimages:

    permissions:
      contents: read
      packages: write
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      REPOSITORY_OWNER: ${{ secrets.REPOSITORY_OWNER }}
    strategy:
     fail-fast: false
     matrix:
      image: [moneyquiz-webadmin,moneyquiz-webclient,moneyquiz-webservice]
      context: [webadmin,webclient,webservice]
      file: [webadmin,webclient,webservice]      
    uses: ./.github/workflows/commonbuild.yml  
    with:
     image: ${{ matrix.image }}
     context: ${{ matrix.context }}
     file: ${{ matrix.file }}

