name: Build & publish image
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
 build-and-push-webadmin:
    strategy:
     matrix:
      image: [ghcr.io/sunnysidigiddi123/moneyquiz-webadmin]
      context: [webadmin]
      file: [./webadmin/Dockerfile]
    permissions:
      contents: read
      packages: write
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      REPOSITORY_OWNER: ${{ secrets.REPOSITORY_OWNER }} 
    uses: ./.github/workflows/commonbuild.yml  
    with:
     image: ${{ matrix.image }}
     context: ${{ matrix.context }}
     file: ${{ matrix.file }}

