name: Build & publish image
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
 build-and-push-dockerimages:
    strategy:
     fail-fast: false
     matrix:
       project: [ webservice]
    permissions:
      contents: read
      packages: write
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      REPOSITORY_OWNER: ${{ secrets.REPOSITORY_OWNER }}  
    uses: ./.github/workflows/commonbuild.yml  
    with:
     image: ${{matrix.project}} 
     context: ${{matrix.project}}
     file: ./${{matrix.project}}/Dockerfile
     
 deploy-to-kubernetes:
    needs: build-and-push-dockerimages
    uses: ./.github/workflows/commondeploy.yml 
    with:
      repository_name: ${{ github.event.repository.name }}
      version: ${{ needs.build-and-push-dockerimages.outputs.version }}
      cluster_environment: testing
    secrets:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}   
