name: Build & publish image
on:
  workflow_call: 
    outputs:
      version:
        description: 'Version'
        value: ${{ jobs.build-docker.outputs.version }}
      cluster_environment:
        description: 'Cluster Environment'
        value: ${{ jobs.build-docker.outputs.cluster_environment }}
    secrets:
      GHCR_TOKEN:
        required: true
        description: 'secret for GHRC'
      REPOSITORY_OWNER:
        required: true
        description: 'username of repository owner'        

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: webadmin
          file: ./webadmin/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
