name: Build & publish image
on:
  workflow_call: 
    inputs:
      context:
        required: true
        type: string
      file:
        required: true
        type: string   
      image:
        required: true
        type: string 
        
    outputs:
      image_name:
        description: 'Image Name'
        value: ${{ jobs.build-and-push-image.outputs.image_name }}    
      version:
        description: 'Version'
        value: ${{ jobs.build-and-push-image.outputs.version }}
      cluster_environment:
        description: 'Cluster Environment'
        value: ${{ jobs.build-and-push-image.outputs.cluster_environment }}
    secrets:
      GHCR_TOKEN:
        required: true
        description: 'secret for GHRC'
      REPOSITORY_OWNER:
        required: true
        description: 'username of repository owner'   
          

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.version.outputs.build_version }}
      cluster_environment: ${{ steps.cluster_environment.outputs.cluster_environment }}      
      image_name: ${{ steps.image_name.outputs.images }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: | 
              ghcr.io/${{ secrets.REPOSITORY_OWNER }}/${{ github.repository }}-${{ inputs.image }}
          tags: |
            type=semver,pattern={{version}}
      - name: Setting application version
        id: version
        run: |
          echo "::set-output name=build_version::${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
      - name: Identifying cluster in which application should be deployed
        id: cluster_environment
        run: |
          if [[ "${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version']}}" =~ .*-rc[0-9] ]]; then
            echo '::set-output name=cluster_environment::testing'
          else
            echo '::set-output name=cluster_environment::production'
          fi            
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
