name: Identify the cluster environment

on:
  workflow_run:
    workflows: ["Build & publish image"]
    types:
      - requested

jobs:
  identify-cluster-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Identifying cluster in which application should be deployed
        run: |
          if [[ "${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version']}}" =~ .*-rc[0-9] ]]; then
            echo '::set-output name=cluster_environment::testing'
          else
            echo '::set-output name=cluster_environment::production'
          fi  